// Generated by Haxe 4.2.0-rc.1+d0fd88b9b
#include <hxcpp.h>

#ifndef INCLUDED_haxe_io_Error
#include <haxe/io/Error.h>
#endif
#ifndef INCLUDED_haxe_io_Encoding
#include <haxe/io/Encoding.h>
#endif
#ifndef INCLUDED_haxe_Log
#include <haxe/Log.h>
#endif
#ifndef INCLUDED_uv__SockAddrIn_SockAddrIn_Impl_
#include <uv/_SockAddrIn/SockAddrIn_Impl_.h>
#endif
#ifndef INCLUDED_uv__Data_Data_Impl_
#include <uv/_Data/Data_Impl_.h>
#endif
#ifndef INCLUDED_haxe_node__Buffer_Buffer_Impl_
#include <haxe/node/_Buffer/Buffer_Impl_.h>
#endif
#ifndef INCLUDED_haxe_iterators_ArrayIterator
#include <haxe/iterators/ArrayIterator.h>
#endif
#ifndef INCLUDED_haxe_io__UInt8Array_UInt8Array_Impl_
#include <haxe/io/_UInt8Array/UInt8Array_Impl_.h>
#endif
#ifndef INCLUDED_haxe_io_Bytes
#include <haxe/io/Bytes.h>
#endif
#ifndef INCLUDED_haxe_io__ArrayBufferView_ArrayBufferView_Impl_
#include <haxe/io/_ArrayBufferView/ArrayBufferView_Impl_.h>
#endif
#ifndef INCLUDED_haxe_io_ArrayBufferViewImpl
#include <haxe/io/ArrayBufferViewImpl.h>
#endif
#ifndef INCLUDED_haxe_ValueException
#include <haxe/ValueException.h>
#endif
#ifndef INCLUDED_haxe_NativeStackTrace
#include <haxe/NativeStackTrace.h>
#endif
#ifndef INCLUDED_haxe_Exception
#include <haxe/Exception.h>
#endif
#ifndef INCLUDED_Foo
#include <Foo.h>
#endif
#ifndef INCLUDED_Test
#include <Test.h>
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif

void __files__boot();

void __boot_all()
{
__files__boot();
::hx::RegisterResources( ::hx::GetResources() );
::haxe::io::Error_obj::__register();
::haxe::io::Encoding_obj::__register();
::haxe::Log_obj::__register();
::uv::_SockAddrIn::SockAddrIn_Impl__obj::__register();
::uv::_Data::Data_Impl__obj::__register();
::haxe::node::_Buffer::Buffer_Impl__obj::__register();
::haxe::iterators::ArrayIterator_obj::__register();
::haxe::io::_UInt8Array::UInt8Array_Impl__obj::__register();
::haxe::io::Bytes_obj::__register();
::haxe::io::_ArrayBufferView::ArrayBufferView_Impl__obj::__register();
::haxe::io::ArrayBufferViewImpl_obj::__register();
::haxe::ValueException_obj::__register();
::haxe::NativeStackTrace_obj::__register();
::haxe::Exception_obj::__register();
::Foo_obj::__register();
::Test_obj::__register();
::Std_obj::__register();
::haxe::io::Error_obj::__boot();
::haxe::io::Encoding_obj::__boot();
::haxe::Log_obj::__boot();
}

