// Generated by Haxe 4.2.0-rc.1+d0fd88b9b
#include <hxcpp.h>

namespace hx {
const char *__hxcpp_all_files[] = {
#ifdef HXCPP_DEBUGGER
"?",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/Std.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/haxe/Exception.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/haxe/Log.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/haxe/NativeStackTrace.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/ValueException.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/io/ArrayBufferView.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/io/Bytes.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/io/UInt8Array.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/iterators/ArrayIterator.hx",
"Test.hx",
"haxe/node/Buffer.hx",
"uv/Data.hx",
"uv/SockAddrIn.hx",
#endif
 0 };

const char *__hxcpp_all_files_fullpath[] = {
#ifdef HXCPP_DEBUGGER
"F:\\project\\libuv\\linc_uv\\test\\?",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\Std.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\haxe\\Exception.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\haxe\\Log.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\haxe\\NativeStackTrace.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\ValueException.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\ArrayBufferView.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\Bytes.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\UInt8Array.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\iterators\\ArrayIterator.hx",
"F:\\project\\libuv\\linc_uv\\test\\Test.hx",
"F:\\project\\libuv\\linc_uv\\haxe\\node\\Buffer.hx",
"F:\\project\\libuv\\linc_uv\\uv\\Data.hx",
"F:\\project\\libuv\\linc_uv\\uv\\SockAddrIn.hx",
#endif
 0 };

const char *__hxcpp_all_classes[] = {
#ifdef HXCPP_DEBUGGER
"Std",
"Test",
"Foo",
"haxe.Exception",
"haxe.Log",
"haxe.NativeStackTrace",
"haxe.ValueException",
"haxe.io.ArrayBufferViewImpl",
"haxe.io._ArrayBufferView.ArrayBufferView_Impl_",
"haxe.io.Bytes",
"haxe.io._UInt8Array.UInt8Array_Impl_",
"haxe.iterators.ArrayIterator",
"haxe.node._Buffer.Buffer_Impl_",
"uv._Data.Data_Impl_",
"uv._SockAddrIn.SockAddrIn_Impl_",
#endif
 0 };
} // namespace hx
void __files__boot() { __hxcpp_set_debugger_info(::hx::__hxcpp_all_classes, ::hx::__hxcpp_all_files_fullpath); }
