// Generated by Haxe 4.2.0-rc.1+d0fd88b9b
#include <hxcpp.h>

namespace hx {
}

::hx::Resource __Resources[] = {
	{ ::String(null()),0,0 }
};

namespace hx { Resource *GetResources() { return __Resources; } }
