// Generated by Haxe 4.2.0-rc.1+d0fd88b9b
#ifndef INCLUDED_haxe_io__UInt8Array_UInt8Array_Impl_
#define INCLUDED_haxe_io__UInt8Array_UInt8Array_Impl_

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS2(haxe,io,ArrayBufferViewImpl)
HX_DECLARE_CLASS2(haxe,io,Bytes)
HX_DECLARE_CLASS3(haxe,io,_UInt8Array,UInt8Array_Impl_)

namespace haxe{
namespace io{
namespace _UInt8Array{


class HXCPP_CLASS_ATTRIBUTES UInt8Array_Impl__obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef UInt8Array_Impl__obj OBJ_;
		UInt8Array_Impl__obj();

	public:
		enum { _hx_ClassId = 0x3bec3945 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="haxe.io._UInt8Array.UInt8Array_Impl_")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"haxe.io._UInt8Array.UInt8Array_Impl_"); }

		inline static ::hx::ObjectPtr< UInt8Array_Impl__obj > __new() {
			::hx::ObjectPtr< UInt8Array_Impl__obj > __this = new UInt8Array_Impl__obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< UInt8Array_Impl__obj > __alloc(::hx::Ctx *_hx_ctx) {
			UInt8Array_Impl__obj *__this = (UInt8Array_Impl__obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(UInt8Array_Impl__obj), false, "haxe.io._UInt8Array.UInt8Array_Impl_"));
			*(void **)__this = UInt8Array_Impl__obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~UInt8Array_Impl__obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("UInt8Array_Impl_",3b,dc,bf,2b); }

		static  ::haxe::io::ArrayBufferViewImpl fromData( ::haxe::io::ArrayBufferViewImpl d);
		static ::Dynamic fromData_dyn();

		static  ::haxe::io::ArrayBufferViewImpl fromBytes( ::haxe::io::Bytes bytes,::hx::Null< int >  bytePos, ::Dynamic length);
		static ::Dynamic fromBytes_dyn();

};

} // end namespace haxe
} // end namespace io
} // end namespace _UInt8Array

#endif /* INCLUDED_haxe_io__UInt8Array_UInt8Array_Impl_ */ 
