// Generated by Haxe 4.2.0-rc.1+d0fd88b9b
#ifndef INCLUDED_uv__SockAddrIn_SockAddrIn_Impl_
#define INCLUDED_uv__SockAddrIn_SockAddrIn_Impl_

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

#ifndef INCLUDED_0f1da2a7ba9c7167
#define INCLUDED_0f1da2a7ba9c7167
#include "linc_uv.h"
#endif
HX_DECLARE_CLASS2(uv,_SockAddrIn,SockAddrIn_Impl_)

namespace uv{
namespace _SockAddrIn{


class HXCPP_CLASS_ATTRIBUTES SockAddrIn_Impl__obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef SockAddrIn_Impl__obj OBJ_;
		SockAddrIn_Impl__obj();

	public:
		enum { _hx_ClassId = 0x33ce498e };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="uv._SockAddrIn.SockAddrIn_Impl_")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"uv._SockAddrIn.SockAddrIn_Impl_"); }

		inline static ::hx::ObjectPtr< SockAddrIn_Impl__obj > __new() {
			::hx::ObjectPtr< SockAddrIn_Impl__obj > __this = new SockAddrIn_Impl__obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< SockAddrIn_Impl__obj > __alloc(::hx::Ctx *_hx_ctx) {
			SockAddrIn_Impl__obj *__this = (SockAddrIn_Impl__obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(SockAddrIn_Impl__obj), false, "uv._SockAddrIn.SockAddrIn_Impl_"));
			*(void **)__this = SockAddrIn_Impl__obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~SockAddrIn_Impl__obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("SockAddrIn_Impl_",1a,6b,6c,2d); }

		static  ::Dynamic getAddress(::cpp::Pointer<  sockaddr_in > this1);
		static ::Dynamic getAddress_dyn();

};

} // end namespace uv
} // end namespace _SockAddrIn

#endif /* INCLUDED_uv__SockAddrIn_SockAddrIn_Impl_ */ 
